[package]
name = "percy-router-macro-test"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"

[dependencies]
percy-router-macro = {path = "../percy-router-macro"}
percy-dom = {path = "../percy-dom"}
percy-router = {path = "../percy-router"}
