services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: bachelor
      MYSQL_PASSWORD: bachelor
      MYSQL_ROOT_PASSWORD: bachelor
      MYSQL_DATABASE: wasi-chat
  redis:
    image: redis:latest
    restart: always
    networks:
      - default
    ports:
      - "16785:6379"
    command: [ "redis-server", "--protected-mode no" ]
