[package]
name = "wasmedge-http-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmedge_http_req = "*"
wasmedge_wasi_socket = "*"
httpcodec = "0.2.3"
bytecodec = "0.4.15"